MONGODB_HOST: mongodb-prod.pkpj.store # submit your host
REDIS_HOST: redis-prod.pkpj.store
MYSQL_HOST: mysql-prod.pkpj.store
RABBITMQ_HOST: rabbitmq-prod.pkpj.store
CATALOGUE_HOST: catalogue-prod.pkpj.store
USER_HOST: user-prod.pkpj.store
CART_HOST: cart-prod.pkpj.store
SHIPPING_HOST: shipping-prod.pkpj.store
PAYMENT_HOST: payment-prod.pkpj.store
DISPATCH_HOST: dispatch-prod.pkpj.store
NEXUS_URL: http://172.31.5.95:8081/repository
group_id: "com/roboshop"